#!/usr/bin/env node
// Generated sources. Every file written here is derived from a source that a
// human edits, and `--check` compares all of them byte for byte so a stale
// generated file cannot ship:
//
//   moon.mod + docs/preshell.md -> cmd/preshell/manual_generated.mbt
//   moon.mod                    -> cmd/preshell/version_generated.mbt
//   moon.mod + docs/preshell.md -> docs/preshell.1
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = dirname(dirname(new URL(import.meta.url).pathname));
const sourcePath = join(root, "docs", "preshell.md");
const modPath = join(root, "moon.mod");
const generatedPath = join(root, "cmd", "preshell", "manual_generated.mbt");
const versionPath = join(root, "cmd", "preshell", "version_generated.mbt");
const manPath = join(root, "docs", "preshell.1");
const markdown = readFileSync(sourcePath, "utf8").replace(/\r\n/g, "\n");

function plainText(input) {
  const lines = input.split("\n");
  const out = [];
  let inCode = false;
  for (const line of lines) {
    if (line.startsWith("```")) {
      inCode = !inCode;
      if (inCode) out.push("");
      continue;
    }
    if (inCode) {
      out.push(line);
      continue;
    }
    if (/^#{1,6} /.test(line)) {
      const title = line.replace(/^#{1,6} /, "");
      out.push(title);
      out.push("-".repeat(Math.max(3, Math.min(title.length, 72))));
      continue;
    }
    if (/^<[^>]+>$/.test(line)) continue;
    let value = line;
    value = value.replace(/^[-*] /, "* ");
    value = value.replace(/^\s*\d+\. /, "  $&");
    value = value.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)");
    value = value.replace(/<([^>]+)>/g, "$1");
    value = value.replace(/`([^`]+)`/g, "$1");
    value = value.replace(/\*\*([^*]+)\*\*/g, "$1");
    value = value.replace(/_([^_]+)_/g, "$1");
    out.push(value);
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function roffEscape(value) {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function roffText(value) {
  return roffEscape(value).replace(/^\./gm, "\\&.");
}

function roffInline(value) {
  const bold = "\u0001";
  const plain = value
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 (<$2>)")
    .replace(/<([^>]+)>/g, "$1")
    .replace(/`([^`]+)`/g, `${bold}B$1${bold}R`)
    .replace(/\*\*([^*]+)\*\*/g, `${bold}B$1${bold}R`);
  return roffText(plain)
    .replaceAll(`${bold}B`, "\\fB")
    .replaceAll(`${bold}R`, "\\fR");
}

// The man page identifies its version from moon.mod rather than a copy, so a
// version bump cannot leave the page claiming the previous one. The date field
// is left empty on purpose: anything clock-derived would make this generator
// non-deterministic, and the drift check compares generated output byte for byte.
function toRoff(input, version) {
  const lines = input.split("\n");
  const out = [
    `.TH PreShell 1 "" "preshell ${version}" "User Commands"`,
    ".SH NAME",
    "preshell \\- report what a shell command touches, as JSON",
  ];
  let inCode = false;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (line.startsWith("```")) {
      inCode = !inCode;
      out.push(inCode ? ".PP\n.nf" : ".fi");
      continue;
    }
    if (inCode) {
      out.push(roffText(line));
      continue;
    }
    const heading = line.match(/^#{1,2} (.+)$/);
    if (heading) {
      if (heading[1].toLowerCase() === "preshell") continue;
      out.push(`.SH ${roffEscape(heading[1].toUpperCase())}`);
      continue;
    }
    if (!line) {
      out.push(".PP");
      continue;
    }
    if (/^- /.test(line)) {
      out.push(`.IP \"\\(bu\" 4\n${roffInline(line.slice(2))}`);
      continue;
    }
    out.push(roffInline(line));
  }
  return out.join("\n").replace(/(\.PP\n){2,}/g, ".PP\n") + "\n";
}

// The version lives in moon.mod and nowhere else: the binary, the man page and
// the module registry all read it from that one line, so a bump cannot leave
// one of them claiming the previous release (0.2.1 needed a separate commit to
// sync a hand-written copy).
const version = readFileSync(modPath, "utf8").match(/^version\s*=\s*"([^"]+)"/m)[1];
const plain = plainText(markdown);
const generated = `///|\n// Generated from docs/preshell.md by tools/codegen.mjs.\n// Do not edit this file directly.\nlet manual_markdown : String = ${JSON.stringify(markdown)}\n\n///|\nlet manual_plain : String = ${JSON.stringify(plain)}\n`;
const versionSource = `///|\n// Generated from moon.mod by tools/codegen.mjs.\n// Do not edit this file directly.\nlet tool_version_baked : String = ${JSON.stringify(version)}\n`;
const outputs = [
  [generatedPath, generated],
  [versionPath, versionSource],
  [manPath, toRoff(markdown, version)],
];
if (process.argv.includes("--check")) {
  for (const [path, expected] of outputs) {
    let actual;
    try { actual = readFileSync(path, "utf8"); } catch { actual = null; }
    if (actual !== expected) {
      console.error(`${path}: generated source is stale; run node tools/codegen.mjs`);
      process.exitCode = 1;
    }
  }
} else {
  for (const [path, content] of outputs) writeFileSync(path, content);
}
